# Snapshot service definition

# No parameters
# A request causes a snapshot to be made

---
# Result code
#
# 0: success
uint8 RESULT_OK = 0
# 1: No laser scan data
uint8 RESULT_NO_LASER_DATA = 1
# 2: Stale laser scan data
uint8 RESULT_STALE_LASER_DATA = 2
# Other values to be determined

uint8 result
